# Generated by Django 4.2.13 on 2024-06-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_his_referral_code_user_referal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referal_code_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Число использований реферального кода пользователя'),
        ),
    ]
