# Generated by Django 4.2.13 on 2024-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_referal_code_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project_completion_percentage',
            field=models.PositiveIntegerField(choices=[(0, 0), (25, 25), (50, 50), (75, 75), (100, 100)], default=0, verbose_name='Процент завершенности проекта'),
        ),
    ]
