# Generated by Django 4.2.13 on 2024-06-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options_alter_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('uses_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='referal_code_used',
            new_name='referral_code_used',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referal_code',
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='users.referralcode'),
        ),
    ]
