# Generated by Django 4.2.13 on 2024-06-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_informations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagramm', models.CharField(max_length=512, verbose_name='Инстаграмм')),
                ('vk', models.CharField(max_length=512, verbose_name='Вконтакте')),
                ('number', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('mail_address', models.CharField(max_length=64, verbose_name='Почта')),
                ('telegramm', models.CharField(max_length=64, verbose_name='Почта')),
                ('mail_for_from', models.CharField(max_length=64, verbose_name='Почта для писем из формы')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Овет')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
            },
        ),
    ]
