# Generated by Django 4.2.13 on 2024-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_informations',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AlterField(
            model_name='contact_informations',
            name='instagramm',
            field=models.CharField(default='None', max_length=512, verbose_name='Инстаграмм'),
        ),
        migrations.AlterField(
            model_name='contact_informations',
            name='mail_address',
            field=models.CharField(default='None', max_length=64, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contact_informations',
            name='mail_for_from',
            field=models.CharField(default='None', max_length=64, verbose_name='Почта для писем из формы'),
        ),
        migrations.AlterField(
            model_name='contact_informations',
            name='number',
            field=models.CharField(default='None', max_length=32, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact_informations',
            name='telegramm',
            field=models.CharField(default='None', max_length=64, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='contact_informations',
            name='vk',
            field=models.CharField(default='None', max_length=512, verbose_name='Вконтакте'),
        ),
        migrations.AlterModelTable(
            name='contact_informations',
            table='contact_info',
        ),
    ]
