# Generated by Django 4.2.13 on 2024-06-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_contact_informations_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_informations',
            name='telegramm',
            field=models.CharField(default='None', max_length=64, verbose_name='Телеграмм'),
        ),
    ]
