# Generated by Django 4.2.13 on 2024-06-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_contact_informations_telegramm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_informations',
            name='number',
            field=models.CharField(default='88', max_length=32, verbose_name='Номер телефона'),
        ),
    ]
